### ISSUE TITLE
Works on Apple Silicon if...

### ISSUE THREAD

**Issue by sparky4pro** [magic003/objc#1]
...the use of `objc_msgSend_stret()` is eliminated, as it's not available on macOS ARM.

Very nice job.

**Comment by magic003** [comment]
@sparkylein thanks for reporting the issue. I have come up with a quick fix in this [PR](https://github.com/magic003/objc/pull/2). I don't have a macOS Apple Silicon device right now, so I couldn't test it. Would you mind taking the PR and testing if it works?

**Comment by sparky4pro** [comment]
The V compiler wants a `return` at the end of `fn get_msg_send_fn[R]() FnSendMsgGeneric`.
Suppose there needs to be a default `return` after the `$if` block.

This is how the function looks on my end:
```v
fn get_msg_send_fn[R]() FnSendMsgGeneric {
	// issue #1. Always use objc_msgSend for Apple Silicon chips.
	$if arm64 {
		return C.objc_msgSend
	} $else {
		// WARNING: this is a very naive way to decide calling objc_msgSend or objc_msgSend_stret.
		// If the size of the return type is less or equal than the C pointer size, it assumes the value
		// can be saved in registers and hence the objc_msgSend is used. Otherwise, objc_msgSend_stret
		// is used. It is only tested on x86_64 and may not work on other architecture.
		ptr_size := sizeof(voidptr)
		if sizeof(R) <= ptr_size {
			return C.objc_msgSend
		} else {
			return C.objc_msgSend_stret
		}
	}
	
	return C.objc_msgSend
}
```
This compiles fine.
Awesome!

EDIT: forgot to mention that I updated V yesterday...

**Comment by magic003** [comment]
Yeah, I am on the latest V version too.

This sounds a little bit weird to me.
1. The `$if-$else` block always has a return statement, no matter which platform it is on. So V compiler should not fail.
2. I replaced `arm64` with `x86` so it should have the same effect on my laptop as that on yours. I didn't see V compiler error but the unit tests failed, which is expected.

Would you please paste the V compiler error you got after running `make`?

At the same time, I have added the  `return C.objc_msgSend` statement at the end, as you did above. I have merged the PR to unblock your usage. :)

**Comment by sparky4pro** [comment]
Here the error message:
```
objc % make build
v -shared .
src/message.v:192:1: error: missing return at end of function `objc.get_msg_send_fn`
  190 | 
  191 | // get_msg_send_fn determines which objc_msgSend* function to call based on `R`.
  192 | fn get_msg_send_fn[R]() FnSendMsgGeneric {
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  193 |     // issue #1. Always use objc_msgSend for Apple Silicon chips.
  194 |     $if arm64 {
make: *** [build] Error 1
```
Suppose this happens because after the `$if` block there is no `return`, as the compiler is not smart enough to recognize the 2 `return` in the `$if` block.
Besides, shouldn’t this error message show up on any OS?

**Comment by magic003** [comment]
Yeah, that's my understanding that it should have the same error message in any OS. But it didn't happen on my laptop with an Intel processor.
